/** Who may use what. Pure data: imported by server guards and client UI alike. */
export type Access = "guest" | "full" | "admin";
export type GuestRule = boolean | "sample";

// memberReason: the one line a guest sees for why a feature is outside the guest tour.
export const FEATURES = {
  tcf: { guest: false, label: "TCF Canada practice", memberReason: "Exam content is available to members only." },
  speaking: {
    guest: false,
    label: "Speaking lab",
    memberReason: "Every recording is scored by a paid speech service, and recordings are personal data.",
  },
  quiz: { guest: false, label: "Quiz and cloze sets", memberReason: "Imports run your own files through paid AI." },
  writing: { guest: false, label: "Writing feedback", memberReason: "Feedback calls paid AI." },
  microDrill: { guest: false, label: "Targeted drills", memberReason: "Drills are generated by paid AI." },
  upload: { guest: false, label: "Adding your own texts", memberReason: "The guest tour uses the sample texts." },
  lookup: { guest: "sample", label: "Word look-up", memberReason: "Look-ups outside the sample texts call paid AI." },
  enrich: { guest: false, label: "Detailed word entries", memberReason: "Full entries are generated by paid AI." },
} as const satisfies Record<string, { guest: GuestRule; label: string; memberReason: string }>;

export type FeatureKey = keyof typeof FEATURES;

/** `true` = full use; `"sample"` = only inside the sample workspace; `false` = locked. */
export function canUse(access: Access, key: FeatureKey): GuestRule {
  return access === "guest" ? FEATURES[key].guest : true;
}

export function deriveAccess(role: string | null | undefined, isAnonymous: boolean | null | undefined): Access {
  if (role === "admin") return "admin";
  return isAnonymous ? "guest" : "full";
}
